version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - test_network

  test:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      - nginx
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
