
services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./$SHARED_DIR:/$SHARED_DIR  # Mounts the shared folder as a shared volume
    container_name: nginx
    ports:
      - $SERVER_PORT_HTML:$SERVER_PORT_HTML
      - $SERVER_PORT_ERROR:$SERVER_PORT_ERROR
    env_file:
      - .env
    networks:
      - test_network

  test:
    build:
      context: ./test
    depends_on:
      - nginx
    container_name: test
    volumes:
      - ./$RESULTS_DIR:/$RESULTS_DIR  # Shared volume with the host
      - ./$SHARED_DIR:/$SHARED_DIR    # Mounts the html folder as a shared volume
    env_file:
      - .env
    networks:
      - test_network

volumes:
  shared_vol:
  results_vol:

networks:
  test_network:
    driver: bridge
