version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
     - "8080:8080"
     - "9090:9090"
    volumes:
      - ./shared:/shared  # Mounts the shared folder as a shared volume
    container_name: nginx
    networks:
      - test_network

  test:
    build:
      context: ./test
    depends_on:
      - nginx
    container_name: test
    volumes:
      - ./results:/results  # Shared volume with the host
      - ./shared:/shared  # Mounts the html folder as a shared volume
    networks:
      - test_network

volumes:
  results:
  shared:

networks:
  test_network:
    driver: bridge
