version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
      - "9090:9090"
    container_name: nginx
    networks:
      - test_network


  test:
    build:
      context: ./test
    depends_on:
      - nginx
    container_name: test
    volumes:
      - ./test-results:/test-results  # Shared volume with the host
    networks:
      - test_network
    environment:
      - NGINX_HOST=nginx
      - RESULTS_DIR=/test-results


volumes:
  test-results:

networks:
  test_network:
    driver: bridge
