name: Docker CI

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Set up Docker compose
      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose
      
      # Build Docker images
      - name: Build Docker Compose services
        run: docker-compose build

      # Start Docker Compose services and run tests
      - name: Start services and run tests
        run: docker-compose up -d  # Start containers in detached mode
      
      - name: Wait for container to finish writing files
        run: sleep 3 

      - name: Display logs in the workflow
        run:  cat ./test-s/logs/test_log.txt

      - name: Find the test results file
        id: find-file
        run: |
          echo "Searching for test results files in test-results/artifacts"
          # List files for debugging purposes
          ls -la ./test-results/artifacts

          # Look for the file named either 'succeeded' or 'fail'
          FILE=$(ls ./test-results/artifacts | grep -E 'succeeded|fail' || echo "no results file found")
          echo "Found test results file: $FILE"

          # If no file is found, exit with a custom error
          if [ "$FILE" == "no results file found" ]; then
            echo "No results file found in artifacts directory."
            exit 1
          fi
          
          # Save the file name to an environment variable for later use
          echo "artifact_name=$FILE" >> $GITHUB_ENV

      - name: Upload the test results artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}  # Dynamically set artifact name
          path: ./test-results/artifacts/${{ env.artifact_name }}  # Upload the file

      # Shut down Docker Compose services
      - name: Stop Docker Compose services
        run: docker-compose down
