name: Docker CI

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Set up Docker compose
      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose
      
      # Build Docker images
      - name: Build Docker Compose services
        run: docker-compose build

      # Start Docker Compose services and run tests
      - name: Start services and run tests
        run: docker-compose up -d  # Start containers in detached mode
      
      - name: Wait for container to finish writing files
        run: sleep 3 

      - name: Display logs in the workflow
        run:  cat ./test-results/logs/test_log.txt
      
      - name: Find the test result file
        id: find-file
        run: |
          # Assuming the file will be in the test-results directory and its name will be either "succeeded" or "fail"
          FILE=$(ls ./test-results | grep -E 'succeeded|fail')
          echo "Found test result file: $FILE"
          # Set the file name as the artifact name
          echo "artifact_name=$FILE" >> $GITHUB_ENV

      - name: Upload the test result artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}  # Use the dynamically set artifact name
          path: ./test-results/${{ env.artifact_name }}  # Upload the corresponding file

      # Shut down Docker Compose services
      - name: Stop Docker Compose services
        run: docker-compose down
