name: Docker CI

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Check out repository
        uses: actions/checkout@v4

      #test
      - name: add execution premission 
        run: chmod +x configure-nginx.sh
      
      # Run the configure_templates.py script
      - name: Configure nginx
        run: configure-nginx.sh

      # Build Docker images
      - name: Build Docker Compose services
        run: docker compose build

      # Start Docker ontainers and run tests
      - name: Start services and run tests
        run: docker compose up -d # Start containers in detached mode

        # Wait for indicative log to verify testing was finished properly
      - name: Ensure Testing was finished
        run: |
          timeout 20s bash -c 'docker compose logs -f test | grep -m 1 "Finished Testing"'

      - name: Find the test results file
        run: |
          echo "Searching for test results files in results"

          # Look for the result file in the artifacts directory
          FILE=$(ls ./results || echo "no results file found")
          echo "Found test results file: $FILE"

          # If no file is found, exit with a custom error
          if [ "$FILE" == "no results file found" ]; then
            echo "No file found in results directory."
            exit 1
          fi
          echo "artifact_name=$FILE" >> $GITHUB_ENV

      - name: Upload the test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }} # Dynamically set artifact name
          path: ./results/${{ env.artifact_name }} # Upload the file

      - name: Stop Docker Compose services
        run: docker compose down
