name: Docker CI

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

  build-and-test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build Docker Compose services
        run: docker compose build

      - name: Start services and run tests
        run: docker compose up -d

      - name: Wait for specific log message
        run: |
          echo "Waiting for test container to complete..."
          docker compose logs -f test-container | grep -q "Test script finished"
          echo "Test container has completed."

      - name: Display logs in the workflow
        run: cat ./test-results/logs/test_log.txt

      - name: Find the test results file
        run: |
          echo "Searching for test results files in test-results/artifacts"
          ls -la ./test-results/artifacts
          FILE=$(ls ./test-results/artifacts | grep -E 'succeeded|fail' || echo "no results file found")
          echo "Found test results file: $FILE"
          if [ "$FILE" == "no results file found" ]; then
            echo "No results file found in artifacts directory."
            exit 1
          fi
          echo "artifact_name=$FILE" >> $GITHUB_ENV

      - name: Upload the test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: ./test-results/artifacts/${{ env.artifact_name }}

  teardown:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Stop Docker Compose services
        run: docker compose down
