name: Docker CI

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out code
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker images
      - name: Build Docker Compose services
        run: docker-compose build

      # Step 4: Start Docker Compose services and run tests
      - name: Start services and run tests
        run: |
          docker-compose up -d  # Start containers in detached mode
          docker-compose logs -f  # Stream logs to follow the output

      # Step 5: Copy test results from the container to GitHub runner
      - name: Copy test results from the container
        run: |
          # Copy the 'test-results' directory from the test container to the host
          docker cp $(docker-compose ps -q test):/test-results ./test-results

      # Step 6: Upload test results as artifact
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/

      # Step 7: Shut down Docker Compose services
      - name: Stop Docker Compose services
        run: docker-compose down
