name: Docker CI

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Set up Docker compose
      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose
      
      # Build Docker images
      - name: Build Docker Compose services
        run: docker-compose build

      # Start Docker Compose services and run tests
      - name: Start services and run tests
        run: docker-compose up -d  # Start containers in detached mode
      
      - name: Wait for container to finish writing files
        run: sleep 3 

      - name: Display logs in the workflow
        run:  cat ./test-results/logs/test_log.txt
      
      # Upload test results as artifact
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results/artifacts/succeeded

      # Shut down Docker Compose services
      - name: Stop Docker Compose services
        run: docker-compose down
