name: Docker CI

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out code
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose
      
      # Step 3: Build Docker images
      - name: Build Docker Compose services
        run: docker-compose build

      # Step 4: Start Docker Compose services and run tests
      - name: Start services and run tests
        run: docker-compose up -d  # Start containers in detached mode
      
      - name: Wait for container to finish writing files
        run: sleep 3  # Adjust as needed to give the container enough time to complete

      - name: Check test results check location
        run:  ls -R test-results #cat ./test-results/logs/test_log.txt  # Optional: Display logs in the workflow
      
      # Step 6: Upload test results as artifact
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/artifacts/*

      # Step 7: Shut down Docker Compose services
      - name: Stop Docker Compose services
        run: docker-compose down
